apiVersion: v1
kind: Pod
metadata: 
  name: postgress-pod
  labels: 
     name: postress-pod
     app:  demo-voting-app
spec: 
  containers: 
  - name: postgres
    image: postgres:9.4
    ports: 
     - containerPort: 5492
