apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: demo-voting-app
    name: readis-serivce
  name: redis
spec: 
  ports: 
    - "port:6379 target:6379"
  selector: 
    app: demo-voting-app             #(links the redis serivce to the label of the redis pod)
    name: redis-pod

