apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
   name:voting-serivce
   app:demo-voting-app
spec: 
  type: LoadBalancer         #(Change the type to LoadBalancer since by defualt it is clusterIP)
  ports: 
  - port: 80
    target: 80
  selector: 
    name: voting-app-pod              #(links the redis serivce to the label of the voting-app pod)
    app: demo-voting-app 

